{% set name = "pygeoda" %}
{% set version = "0.0.8.post2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GeoDaCenter/pygeoda/archive/v{{ version }}.tar.gz
  sha256: f4ab26c147b59089c595fe8625171b64a4165a517b44dfaa9608548ed4102e6c

build:
  number: 0
  skip: true  # [py<35]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pygeoda

about:
  home: https://github.com/geodacenter/pygeoda
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: pygeoda is a python library for spatial data analysis
  description: |
    pygeoda is a python library for spatial data analysis based on libgeoda and GeoDa. 
    It provides spatial data analysis functionalities including Exploratory Spatial 
    Data Analysis, Spatial Cluster Detection and Clustering Analysis, Regionalization, 
    etc. based on the C++ source code of GeoDa, which is an open-source software tool 
    that serves as an introduction to spatial data analysis. 

  dev_url: https://github.com/geodacenter/pygeoda
  doc_url: https://geodacenter.github.io/pygeoda
  doc_source_url: https://github.com/GeoDaCenter/pygeoda/tree/master/docsrc/source/index.rst

extra:
  recipe-maintainers:
    - lixun910
